### ISSUE TITLE
Image and attachemnt uploads all failing

### ISSUE THREAD

**Issue by impactfactory** [FlusherDock1/EditorJS#10]
**Describe the bug**
- on Chrome
- installed editorJS on system in progress for use in Rainlab Pages and Rainlab Blog
- on domain with sub.domain.ch/, htaccess Rewrite On with simple /
- Text, Tables and so on work fine, appearance very neat, thats how a October Editor should be in my head since years, yeah!
- with trying to upload an image or attachement file can be selected but upload failes (little message box at left corner appears)

**Additional context**
I wonder why the media manager is not coming up for the picture/attachement functionality, would make sense, wouldnt it?

Thank you for the nice work and support also.

**Comment by FlusherDock1** [comment]
Thanks for the report!

**Comment by ventie30** [comment]
Hi @impactfactory. I had the same issue, the upload JS script was trying to call http://localhost/editorjs/plugins/image/uploadFile. In my local setup, the application is served on http://localhost:8000 so that url didn't work. To make it work I had to edit config/app.php, chanign url to be http://localhost:8000.

That worked. There could be a better place to override that such as an .env file, but I'm really new to October and I can't suggest you a better solution.

**Comment by FlusherDock1** [comment]
@ventie30 thanks for the resolving problem!
